name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the artifact to deploy
                required: false
                default: dist
                type: string

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: echo "This is a reusable workflow for deployment!"

