name: Reusable Deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: echo "This is a reusable workflow for deployment!"

